#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Project Euler Problem 45:

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle    T(n)=n(n+1)/2   1, 3, 6, 10, 15, ...
Pentagonal  P(n)=n(3n−1)/2  1, 5, 12, 22, 35, ...
Hexagonal   H(n)=n(2n−1)    1, 6, 15, 28, 45, ...
It can be verified that T(285) = P(165) = H(143) = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

from itertools import count
from math import sqrt

def gen_triangles(start=286):
  yield from map(lambda n: n*(n+1)//2, count(start))

def is_pentagonal(n):
  return sqrt(24*n + 1) % 6 == 5

def is_hexagonal(n):
  return sqrt(8*n + 1) % 4 == 3

print(next(n for n in gen_triangles() if is_pentagonal(n) and is_hexagonal(n)))
